message: client changed default
management:
    security:
        enabled:false
server:
    port: 8885
spring:
    application:
        name: configserver_client
    cloud:
        config:
            uri: http://localhost:8884

eureka:
    client:
        register-with-eureka:true
        fetch-registry:true
        serviceUrl:
            defaultZone: http://localhost:8883/eureka
            
    instance:
        appname: client-service
    instance:
        hostname: localhost
        