message: client changed default
management:
    security:
        enabled: false
server:
    port: 8885
spring:
    application:
        name: configserver_client
    cloud:
        config:
            uri: http://localhost:8887
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8883/eureka   
        register-with-eureka: true
        fetch-registry: true   
    instance:
        appname: client-service
        hostname: localhost