management:
    security:
        enabled: false
server:
    port: 8875
spring:
    application:
        name: cosmosDB-service
    cloud:
        config:
            uri: http://configserver-service:8887
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-service:8883/eureka   
        register-with-eureka: true
        fetch-registry: true   
    instance:
        appname: cosmosDB-service
        hostname: serviceregistry-service