server:
    port: 8883
management:
    security:
        enabled: false
eureka:
    instance:
        hostname: serviceregistry-service
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://serviceregistry-service:8883/eureka/
    server:
        wait-time-in-ms-when-sync-empty: 0
spring:
    application:
        name: eureka_service
    cloud:
        config:
            uri: http://configserver_service:8887