server:
    port: 8883
management:
    security:
        enabled: false
eureka:
    instance:
        hostname: eureka-service
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://eureka-service:8883/eureka/
    server:
        wait-time-in-ms-when-sync-empty: 0
spring:
    application:
        name: eureka-service
    cloud:
        config:
            uri: http://configserver-service:8887