server:
    port:8883
management:
    security:
        enabled:false
eureka:
    client:
        register-with-eureka:false
        fetch-registry:false
        serviceUrl.defaultZone= http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        wait-time-in-ms-when-sync-empty:0
    instance:
        hostname:localhost
        
spring:
    application:
        name: eureka_service
    cloud:
        config:
            uri: http://localhost:8887