eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl.defaultZone: http://localhost:8883/eureka
    instance:
        appname: gateway-service
        hostname: localhost
server:
    port: 8870
    
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: message
        uri: http://localhost:8885/rest/message
        predicates:
            - Path=/message
    config:
      uri: http://localhost:8884